[package]
name = "trix"
version = "0.1.0"
authors = ["Tom Hunger <tehunger@gmail.com>"]
edition = "2018"
build = "build.rs"


[dependencies]
gc-arena = "0.2.0"
lalrpop-util = "0.17.2"

[build-dependencies]
rflex = "0.5.0"
lalrpop = "0.17.2"
proptest = "0.9.5"
